# @package _global_

# Optuna hyperparameter optimization for ResNet models on CIFAR10
# Run command: python src/train.py -m hparams_search=mnist_optuna experiment=exp1.yaml trainer=gpu

defaults:
  - override /hydra/sweeper: optuna

optimized_metric: "val/acc_best"

hydra:
  mode: "MULTIRUN"

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1
    direction: maximize
    n_trials: 20
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 1234
      n_startup_trials: 10

    params:
      data.batch_size: choice(128, 256, 512)
      model.optimizer.lr: interval(0.001, 0.03)
      model.scheduler.step_size: choice(40,60,100)
      model.scheduler.gamma: interval(0.01,0.1)
#       model.loss_coefficient: interval(0.01, 0.2)
#       model.feature_loss_coefficient: interval(0.01, 0.99)
#       model.temperature: interval(5.0, 10)
      trainer.max_epochs: 300  # Fixed to 300 epochs
