_target_: src.models.exp7_1_module.SalmonLitModule

# Define the IntegratedResNet configuration
integrated_resnet:
  _target_: src.models.components.exp7_5_model.IntegratedResNet
  architecture: "resnet18"
  num_classes: 10
  rpu_config:
    _target_: aihwkit.simulator.presets.ReRamSBPreset
    device:
      _target_: aihwkit.simulator.presets.devices.ReRamSBPresetDevice
      dw_min: 0.0002
      dw_min_dtod: 0.0  # Device-to-device variation for minimum weight change disabled
      dw_min_std: 0.0   # Standard deviation for cycle-to-cycle noise for minimum weight change disabled
      up_down: 0.0      # No asymmetry in up and down updates
      up_down_dtod: 0.0 # Device-to-device variation for up_down parameter disabled
      w_max: 1.0        # Maximum weight value
      w_min: -1.0       # Minimum weight value
      w_max_dtod: 0.0   # Device-to-device variation for maximum weight disabled
      w_min_dtod: 0.0   # Device-to-device variation for minimum weight disabled
      mult_noise: false # Multiplier noise disabled
      write_noise_std: 0.0 # Standard deviation for write noise disabled

# 4비트: 0.125
# 5비트: 0.0625
# 6비트: 0.03125
# 7비트: 0.015625
# 8비트: 0.0078125
# 9비트: 0.00390625
# 10비트: 0.001953125
# 11비트: 0.0009765625
# 12비트: 0.00048828125
# 13비트: 0.000244140625
# 14비트: 0.0001220703125
    
# Optimizer settings
optimizer:
  lr: 0.01
  weight_decay: 0.0
  # SGD를 사용하므로, Adam에 특화된 betas, eps, amsgrad 매개변수는 제거
  momentum: 0.9  # SGD에 자주 사용되는 momentum 매개변수 추가
  # 필요한 경우 dampening과 nesterov 매개변수를 추가할 수 있습니다. 예시에서는 생략
  # dampening: 0  # 선택적
  # nesterov: False  # 선택적

# Additional hyperparameters
compile: false
model: "resnet18"
dataset: "cifar10"
epoch: 300
loss_coefficient: 0.0
feature_loss_coefficient: 0.0
dataset_path: "data"
autoaugment: False
temperature: 3
batchsize: 128
init_lr: 0.1
N_CLASSES: 10
block: BasicBlock
alpha: 0.3
p_max: 10000
opt_config : "AnalogSGD"
sch_config : "off-schedule"
sd_config : "true"
FC_Digit : "true"