wandb_version: 1

N_CLASSES:
  value: 19
alpha:
  value: 0.17730339371308773
autoaugment:
  value: 'false'
batch_size:
  value: 39
batchsize:
  value: 128
block:
  value: BasicBlock
callbacks.early_stopping._target_:
  value: lightning.pytorch.callbacks.EarlyStopping
callbacks.early_stopping.check_finite:
  value: 'true'
callbacks.early_stopping.mode:
  value: max
callbacks.early_stopping.monitor:
  value: val/acc
callbacks.early_stopping.patience:
  value: 153
callbacks.early_stopping.strict:
  value: 'false'
callbacks.early_stopping.verbose:
  value: 'false'
callbacks.model_checkpoint._target_:
  value: lightning.pytorch.callbacks.ModelCheckpoint
callbacks.model_checkpoint.auto_insert_metric_name:
  value: 'true'
callbacks.model_checkpoint.dirpath:
  value: ${paths.output_dir}/checkpoints
callbacks.model_checkpoint.filename:
  value: epoch_{epoch:03d}
callbacks.model_checkpoint.mode:
  value: max
callbacks.model_checkpoint.monitor:
  value: val/acc
callbacks.model_checkpoint.save_last:
  value: 'false'
callbacks.model_checkpoint.save_top_k:
  value: 2
callbacks.model_checkpoint.save_weights_only:
  value: 'false'
callbacks.model_checkpoint.verbose:
  value: 'false'
callbacks.model_summary._target_:
  value: lightning.pytorch.callbacks.RichModelSummary
callbacks.model_summary.max_depth:
  value: 0
callbacks.rich_progress_bar._target_:
  value: lightning.pytorch.callbacks.RichProgressBar
compile:
  value: 'false'
data._target_:
  value: src.data.cifar10_datamodule.CIFAR10DataModule
data.batch_size:
  value: 54
data.data_dir:
  value: ${paths.data_dir}
data.num_workers:
  value: 7
data.pin_memory:
  value: 'true'
data_dir:
  value: /root/SALMON/data/
dataset:
  value: cifar10
dataset_path:
  value: data
epoch:
  value: 191
extras.enforce_tags:
  value: 'false'
extras.ignore_warnings:
  value: 'false'
extras.print_config:
  value: 'true'
feature_loss_coefficient:
  value: 0.266024934622765
init_lr:
  value: 0.08646335294332293
loss_coefficient:
  value: 0.3109244298054557
model:
  value: resnet10
model._target_:
  value: src.models.exp2_resnet_SD_digit.SalmonLitModule
model.batch_size:
  value: 43
model.compile:
  value: 'false'
model.integrated_resnet._target_:
  value: src.models.components.salmon.IntegratedResNet
model.integrated_resnet.architecture:
  value: resnet10
model.integrated_resnet.num_classes:
  value: 5
model.net._target_:
  value: src.models.components.salmon.IntegratedResNet
model.net.num_classes:
  value: 18
model.num_workers:
  value: 3
model.optimizer._partial_:
  value: 'false'
model.optimizer._target_:
  value: torch.optim.Adam
model.optimizer.lr:
  value: 0.09696155951497797
model.scheduler._partial_:
  value: 'true'
model.scheduler._target_:
  value: torch.optim.lr_scheduler.StepLR
model.scheduler.factor:
  value: 0.06142692139596513
model.scheduler.gamma:
  value: 0.06492164564422402
model.scheduler.mode:
  value: min
model.scheduler.patience:
  value: 35
model.scheduler.step_size:
  value: 39
model/params/total:
  value: 15268315
model/params/trainable:
  value: 6872786
num_workers:
  value: 6
p_max:
  value: 1886
pin_memory:
  value: 'true'
seed:
  value: 7901
task_name:
  value: train
temperature:
  value: 57.51314405759848
trainer._target_:
  value: lightning.pytorch.trainer.Trainer
trainer.accelerator:
  value: gpu
trainer.check_val_every_n_epoch:
  value: 1
trainer.default_root_dir:
  value: ${paths.output_dir}
trainer.deterministic:
  value: 'false'
trainer.devices:
  value: 2
trainer.gradient_clip_val:
  value: 0.8318606559973095
trainer.max_epochs:
  value: 57
trainer.min_epochs:
  value: 10
